version: "3.5"

services:
  gve_devnet_dnac_port_scheduler:
    image: ghcr.io/gve-sw/gve_devnet_dnac_port_scheduler:latest
    container_name: gve_devnet_dnac_port_scheduler
    environment:
      - DNAC_HOST=
      - DNAC_USER=
      - DNAC_PASSWORD=
      - DNAC_PROJECT_NAME=
      - DNAC_TEMPLATE_NAME=
    volumes:
      - config.yaml:/app/config.yaml
    restart: "always"
